require:
  - 'rubocop-rails'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

# Style/Encoding:
  # EnforcedStyle: never
  # Enabled: true

# Style/FrozenStringLiteralComment:
  # EnforcedStyle: never

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

